"""P5 — Runtime tracing via sys.monitoring (≥3.12) or sys.setprofile (<3.12).

Instruments the target's test suite to capture actual call edges.
The tracer is injected via a pytest conftest.py so the target's tests
run unchanged.

Mechanism choice (per TRD §7.1):
  - sys.monitoring (PEP 669, Python 3.12+): low-overhead PY_START events.
  - sys.setprofile (<3.12): call-granular, no per-line overhead.
  - sys.settrace: NOT the default — fires per-line, too heavy.
"""
from __future__ import annotations

import os
import subprocess
import sys
import json
import tempfile
from pathlib import Path
from typing import Optional

from pyviz.models import ModuleMap, RuntimeEdge


def run_runtime_trace(
    repo_path: str,
    module_map: ModuleMap,
    test_command: str = "pytest -q",
    tracer_backend: str = "auto",
) -> list[RuntimeEdge]:
    """Run the target's test suite with instrumentation; return raw call edges."""
    # Write a temporary conftest.py that installs the tracer and writes results
    edges_file = Path(tempfile.mktemp(suffix="_pyviz_edges.json"))
    conftest_src = _build_conftest(
        source_roots=module_map.source_roots,
        edges_file=str(edges_file),
        tracer_backend=tracer_backend,
    )

    # Inject conftest into the repo root (backed up / restored)
    conftest_path = Path(repo_path) / "conftest_pyviz_tracer.py"
    try:
        conftest_path.write_text(conftest_src, encoding="utf-8")
        cmd = test_command.split() + [f"--co", "-q", "--tb=no"]
        # First, do a dry-run collect to verify the test suite is discoverable
        collect_result = subprocess.run(
            cmd, cwd=repo_path, capture_output=True, text=True, timeout=30
        )

        # Run the actual test suite with our conftest active
        actual_cmd = test_command.split()
        result = subprocess.run(
            actual_cmd,
            cwd=repo_path,
            capture_output=True,
            text=True,
            timeout=300,
            env={**os.environ, "PYVIZ_EDGES_FILE": str(edges_file)},
        )
    finally:
        conftest_path.unlink(missing_ok=True)

    if not edges_file.exists():
        return []

    try:
        raw = json.loads(edges_file.read_text(encoding="utf-8"))
        edges_file.unlink(missing_ok=True)
    except (json.JSONDecodeError, OSError):
        return []

    return [
        RuntimeEdge(
            caller_relpath=e["caller_relpath"],
            caller_qualname=e["caller_qualname"],
            callee_relpath=e["callee_relpath"],
            callee_qualname=e["callee_qualname"],
            count=e["count"],
        )
        for e in raw
    ]


def _build_conftest(
    source_roots: list[str],
    edges_file: str,
    tracer_backend: str,
) -> str:
    """Generate a self-contained pytest conftest.py that captures call edges."""
    roots_repr = repr(source_roots)
    edges_file_repr = repr(edges_file)
    backend_repr = repr(tracer_backend)

    return f'''\
"""Auto-generated by pyviz — runtime call tracer. Do not edit."""
import sys
import os
import json
import collections
from pathlib import Path

_SOURCE_ROOTS = {roots_repr}
_EDGES_FILE = {edges_file_repr}
_BACKEND = {backend_repr}

_edges = collections.defaultdict(int)

def _norm_path(path):
    """POSIX-normalize a path, making it relative to the nearest source root."""
    p = Path(path).resolve()
    for root in _SOURCE_ROOTS:
        try:
            rel = p.relative_to(root)
            return rel.as_posix()
        except ValueError:
            continue
    return None  # outside all source roots

def _is_internal(relpath):
    return relpath is not None


if _BACKEND == "auto":
    _USE_MONITORING = sys.version_info >= (3, 12)
else:
    _USE_MONITORING = _BACKEND == "monitoring"


if _USE_MONITORING:
    # sys.monitoring backend (Python 3.12+)
    _TOOL_ID = sys.monitoring.PROFILER_ID

    def _pycall_handler(code, instruction_offset, callable, arg0):
        callee_file = getattr(code, "co_filename", None)
        callee_qn = getattr(code, "co_qualname", getattr(code, "co_name", ""))
        if callee_file is None:
            return sys.monitoring.DISABLE
        callee_rel = _norm_path(callee_file)
        if not _is_internal(callee_rel):
            return sys.monitoring.DISABLE
        frame = sys._getframe(1)
        caller_file = frame.f_code.co_filename
        caller_qn = getattr(frame.f_code, "co_qualname", frame.f_code.co_name)
        caller_rel = _norm_path(caller_file)
        if _is_internal(caller_rel):
            key = (caller_rel, caller_qn, callee_rel, callee_qn)
            _edges[key] += 1
        return sys.monitoring.DISABLE

    def _install_tracer():
        sys.monitoring.use_tool_id(_TOOL_ID, "pyviz")
        sys.monitoring.set_events(_TOOL_ID, sys.monitoring.events.PY_START)
        sys.monitoring.register_callback(_TOOL_ID, sys.monitoring.events.PY_START, _pycall_handler)

    def _remove_tracer():
        sys.monitoring.set_events(_TOOL_ID, 0)
        sys.monitoring.free_tool_id(_TOOL_ID)

else:
    # sys.setprofile backend (Python < 3.12)
    def _profile_handler(frame, event, arg):
        if event not in ("call", "c_call"):
            return
        callee_file = frame.f_code.co_filename
        callee_qn = getattr(frame.f_code, "co_qualname", frame.f_code.co_name)
        callee_rel = _norm_path(callee_file)
        if not _is_internal(callee_rel):
            return
        caller_frame = frame.f_back
        if caller_frame is None:
            return
        caller_file = caller_frame.f_code.co_filename
        caller_qn = getattr(caller_frame.f_code, "co_qualname", caller_frame.f_code.co_name)
        caller_rel = _norm_path(caller_file)
        if _is_internal(caller_rel):
            key = (caller_rel, caller_qn, callee_rel, callee_qn)
            _edges[key] += 1

    def _install_tracer():
        sys.setprofile(_profile_handler)
        import threading
        threading.setprofile(_profile_handler)

    def _remove_tracer():
        sys.setprofile(None)
        import threading
        threading.setprofile(None)


def pytest_sessionstart(session):
    _install_tracer()


def pytest_sessionfinish(session, exitstatus):
    _remove_tracer()
    result = [
        {{
            "caller_relpath": k[0],
            "caller_qualname": k[1],
            "callee_relpath": k[2],
            "callee_qualname": k[3],
            "count": v,
        }}
        for k, v in _edges.items()
    ]
    Path(_EDGES_FILE).write_text(json.dumps(result), encoding="utf-8")
'''
